name: Daily Market Analysis

on:
  schedule:
    # Run at 9:30 AM EST (14:30 UTC)
    - cron: '30 14 * * 1-5'  # Monday to Friday
  workflow_dispatch:  # Allow manual trigger

jobs:
  market-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy pandas matplotlib seaborn requests
        
    - name: Run market analysis
      env:
        DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1332276762603683862/aKE2i67QHm-1XR-HsMcQylaS0nKTS4yCVty4-jqvJscwkr6VRTacvLhP89F-4ABFDoQw"
      run: |
        python market_analysis.py --discord
