name: UWS Market Analysis

on:
  schedule:
    # To change the time:
    # '04 15 * * 1-5' means:
    #   04 = minute (0-59)
    #   15 = hour in UTC (15 UTC = 10 AM EST)
    #   * = any day of month
    #   * = any month
    #   1-5 = Monday to Friday
    - cron: '9 15 * * 1-5'  # Runs at 10:04 AM EST (15:04 UTC)
  workflow_dispatch:  # Manual trigger with optional inputs
    inputs:
      run_type:
        description: 'Run type (scheduled run at 10:04 AM EST will still occur)'
        required: true
        default: 'auto'
        type: choice
        options:
          - auto
          - discord
          - print

permissions:
  contents: read
  actions: write

jobs:
  market-analysis:
    runs-on: ubuntu-latest
    timeout-minutes: 5  # Reduced timeout for more precise timing
    
    steps:
    - name: Debug Info
      run: |
        echo "Event name: ${{ github.event_name }}"
        echo "Current time: $(date +"%Y-%m-%d %H:%M:%S.%N %Z")"
        echo "Timezone info: $(date +%Z) $(date +%z)"
        echo "Next scheduled run: 10:04 AM EST"
    
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance numpy pandas matplotlib seaborn requests
        
    - name: Run market analysis
      env:
        DISCORD_WEBHOOK_URL: "https://discord.com/api/webhooks/1332276762603683862/aKE2i67QHm-1XR-HsMcQylaS0nKTS4yCVty4-jqvJscwkr6VRTacvLhP89F-4ABFDoQw"
      run: |
        # Wait for exact second if needed
        current_sec=$(date +%S)
        if [ $current_sec -lt 58 ]; then
          sleep_time=$((60 - $current_sec))
          echo "Waiting $sleep_time seconds to start on the minute..."
          sleep $sleep_time
        fi
        
        echo "Starting market analysis at $(date +"%Y-%m-%d %H:%M:%S.%N %Z")"
        
        if [ "${{ github.event_name }}" = "schedule" ] || [ "${{ github.event.inputs.run_type }}" = "auto" ]; then
          # Scheduled or manual auto run
          echo "Running auto analysis..."
          python UWS.py --auto
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "Note: Daily scheduled run will still occur at 10:04 AM EST"
          fi
        elif [ "${{ github.event.inputs.run_type }}" = "print" ]; then
          # Manual run - print to console
          echo "Running manual analysis (print to console)..."
          python UWS.py --print
          echo "Note: Daily scheduled run will still occur at 10:04 AM EST"
        else
          # Manual run - send to Discord
          echo "Running manual analysis (send to Discord)..."
          python UWS.py --discord
          echo "Note: Daily scheduled run will still occur at 10:04 AM EST"
        fi
        
        echo "Finished market analysis at $(date +"%Y-%m-%d %H:%M:%S.%N %Z")"
